# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.EmailField(blank=True, max_length=100, unique=True, verbose_name='email')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('facebook', models.CharField(blank=True, max_length=100, verbose_name='facebook')),
                ('pais', models.CharField(max_length=100, verbose_name='país')),
                ('dataInicio', models.DateField(verbose_name='data de início das atividades')),
                ('dataFim', models.DateField(blank=True, verbose_name='data de término das atividades')),
                ('atividade', models.CharField(max_length=100, verbose_name='atividade ou função')),
                ('status', models.CharField(choices=[('AT', 'Ativo'), ('IN', 'Inativo')], default='AT', editable=False, max_length=2, verbose_name='status')),
            ],
            options={
                'verbose_name': 'membro',
                'verbose_name_plural': 'membros',
            },
        ),
    ]
