# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0002_remove_membro_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='atividade_ingles',
            field=models.CharField(blank=True, max_length=100, verbose_name='atividade ou função em inglês'),
        ),
        migrations.AddField(
            model_name='membro',
            name='depoimento',
            field=models.TextField(blank=True, verbose_name='depoimento'),
        ),
        migrations.AddField(
            model_name='membro',
            name='depoimento_ingles',
            field=models.TextField(blank=True, verbose_name='depoimento em inglês'),
        ),
        migrations.AddField(
            model_name='membro',
            name='pais_ingles',
            field=models.CharField(blank=True, max_length=100, verbose_name='país em inglês'),
        ),
    ]
