# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0004_auto_20171119_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='atividade_ingles',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='atividade ou função em inglês'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membro',
            name='depoimento',
            field=models.TextField(blank=True, default='', verbose_name='depoimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membro',
            name='depoimento_ingles',
            field=models.TextField(blank=True, default='', verbose_name='depoimento em inglês'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membro',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100, unique=True, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membro',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='facebook'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membro',
            name='pais_ingles',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='país em inglês'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membro',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='telefone'),
            preserve_default=False,
        ),
    ]
