# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0005_auto_20171119_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='dataFim',
            field=models.DateField(blank=True, null=True, verbose_name='data de término das atividades'),
        ),
    ]
