# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0006_auto_20171119_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('publico', models.CharField(choices=[('P1', 'CRIANÇAS'), ('P2', 'ADULTOS'), ('P3', 'TODOS')], max_length=2, verbose_name='público alvo')),
                ('dataInicio', models.DateField(verbose_name='data de início do projeto')),
                ('dataFim', models.DateField(blank=True, null=True, verbose_name='data de término do projeto, se houver')),
                ('linkFotos', models.URLField(blank=True, verbose_name='link para álbum de fotos do projeto')),
                ('linkVideo', models.URLField(blank=True, verbose_name='link para vídeo do projeto')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='nome em inglês')),
                ('description', models.TextField(blank=True, verbose_name='descrição em inglês')),
                ('public', models.CharField(blank=True, choices=[('E1', 'CHILDREN'), ('E2', 'ADULTS'), ('E3', 'EVERYONE')], max_length=2, verbose_name='público alvo em inglês')),
            ],
            options={
                'verbose_name': 'projeto',
                'verbose_name_plural': 'projetos',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='membro',
            options={'ordering': ['pais'], 'verbose_name': 'membro', 'verbose_name_plural': 'membros'},
        ),
        migrations.RenameField(
            model_name='membro',
            old_name='atividade_ingles',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='membro',
            old_name='pais_ingles',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='membro',
            old_name='depoimento_ingles',
            new_name='statement',
        ),
        migrations.AlterField(
            model_name='membro',
            name='dataFim',
            field=models.DateField(blank=True, null=True, verbose_name='data de término das atividades, se houver'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='membros',
            field=models.ManyToManyField(blank=True, to='ong.Membro', verbose_name='membros responsáveis pelo projeto'),
        ),
    ]
