# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0008_campanhaparadoacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanhaparadoacoes',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='título em inglês'),
        ),
    ]
