# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0009_auto_20171119_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanhaparadoacoes',
            name='link',
            field=models.URLField(verbose_name='link para campanha (onde o dinheiro é arrecadado)'),
        ),
    ]
