# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0013_auto_20171119_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome do parceiro (Exemplo: USP ou UFSCar')),
                ('responsavel', models.CharField(blank=True, max_length=100, verbose_name='nome do responsável ou pessoa para contato principal (Exemplo: Renan)')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone principal para contato')),
                ('endereco', models.CharField(blank=True, max_length=300, verbose_name='endereço do parceiro')),
                ('link', models.URLField(blank=True, verbose_name='link para site ou página do parceiro')),
            ],
            options={
                'verbose_name': 'parceria',
                'verbose_name_plural': 'parcerias',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='projeto',
            name='membros',
            field=models.ManyToManyField(blank=True, to='ong.Membro', verbose_name='membros responsáveis pelo projeto, se houver'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='parceiros',
            field=models.ManyToManyField(blank=True, to='ong.Parceria', verbose_name='parceiros envolvidos com o projeto, se houver'),
        ),
    ]
