# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0015_auto_20171119_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitadedoacoes',
            name='anonimo',
            field=models.BooleanField(verbose_name='doação anônima? (Marque este campo caso positivo, deixe em branco caso contrário)'),
        ),
    ]
