# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0016_auto_20171119_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitadedoacoes',
            name='usage',
            field=models.CharField(choices=[('E1', 'Administration and maintenance tasks'), ('E2', 'Investments on existing projects'), ('E3', 'Creation of new projects'), ('E4', 'Resources and materials acquisition'), ('E5', 'Training of team members'), ('E6', 'Events and celebrations'), ('E7', 'Other demands')], max_length=2, verbose_name='[INGLÊS] Como esse valor foi gasto/utilizado pela ONG, em ingles'),
        ),
    ]
