# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0018_auto_20171119_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceria',
            name='tipo',
            field=models.CharField(choices=[('P1', 'COMUNIDADE'), ('P2', 'UNIVERSIDADE'), ('P3', 'EMPRESA')], default='', max_length=2, verbose_name='tipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parceria',
            name='type',
            field=models.CharField(choices=[('P1', 'COMMUNITY'), ('P2', 'UNIVERSITY'), ('P3', 'COMPANY')], default='', max_length=2, verbose_name='[INGLÊS] Tipo, em inglês'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campanhaparadoacoes',
            name='description',
            field=models.TextField(blank=True, verbose_name='[INGLÊS] Descrição, em inglês'),
        ),
        migrations.AlterField(
            model_name='campanhaparadoacoes',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='[INGLÊS] Título, em inglês'),
        ),
        migrations.AlterField(
            model_name='depoimentosobreprojeto',
            name='statement',
            field=models.TextField(blank=True, verbose_name='[INGLÊS] Depoimento, em inglês'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='activity',
            field=models.CharField(blank=True, max_length=100, verbose_name='[INGLÊS] Atividade ou função, em inglês'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='[INGLÊS] País, em inglês'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='statement',
            field=models.TextField(blank=True, verbose_name='[INGLÊS] Depoimento, em inglês'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='description',
            field=models.TextField(blank=True, verbose_name='[INGLÊS] Descrição, em inglês'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='[INGLÊS] Nome, em inglês'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='public',
            field=models.CharField(choices=[('E1', 'CHILDREN'), ('E2', 'ADULTS'), ('E3', 'EVERYONE')], max_length=2, verbose_name='[INGLÊS] Público alvo, em inglês'),
        ),
    ]
