# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0021_remove_membro_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceria',
            name='type',
            field=models.CharField(choices=[('E1', 'COMMUNITY'), ('E2', 'UNIVERSITY'), ('E3', 'COMPANY')], max_length=2, verbose_name='[INGLÊS] Tipo, em inglês'),
        ),
        migrations.AlterField(
            model_name='receitadedoacoes',
            name='meio_pagto',
            field=models.CharField(choices=[('PM1', 'PayPal'), ('PM2', 'Vakinha'), ('PM3', 'Boleto'), ('PM4', 'Depósito Bancário'), ('PM5', 'Transferência Bancária'), ('PM5', 'Dinheiro'), ('PM7', 'Outro')], max_length=3, verbose_name='meio de pagamento utilizado pelo doador'),
        ),
        migrations.AlterField(
            model_name='receitadedoacoes',
            name='pay_method',
            field=models.CharField(choices=[('EM1', 'PayPal'), ('EM2', 'Vakinha'), ('EM3', 'Boleto'), ('EM4', 'Bank Deposit'), ('EM5', 'Bank Transfer'), ('EM5', 'Cash'), ('EM7', 'Other')], max_length=3, verbose_name='[INGLÊS] Meio de pagamento utilizado pelo doador, em inglês'),
        ),
    ]
