# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0022_auto_20171125_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='ong/static/images/', verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='membro',
            name='photo64',
            field=models.TextField(editable=False, null=True),
        ),
    ]
