# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0025_auto_20171128_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='atividade',
            field=models.CharField(blank=True, max_length=100, verbose_name='atividade ou função'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='photo64',
            field=models.TextField(blank=True, null=True, verbose_name='foto (se preenchido, foto já existe no sistema)'),
        ),
    ]
