# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0027_auto_20171128_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='apagarPhoto',
            field=models.BooleanField(default=False, verbose_name='marque esta opção se deseja excluir foto ao salvar'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='activity',
            field=models.CharField(blank=True, max_length=100, verbose_name='Atividade ou função, em inglês'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='País, em inglês'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='photo64',
            field=models.TextField(blank=True, null=True, verbose_name='foto (se este campo estiver preenchido, foto já existe no sistema)'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='statement',
            field=models.TextField(blank=True, verbose_name='Depoimento, em inglês'),
        ),
    ]
