# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0029_auto_20171128_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='apagarPhoto',
            field=models.BooleanField(default=False, verbose_name='marque esta opção apenas se deseja excluir a foto ao salvar'),
        ),
    ]
