# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0030_auto_20171128_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='activity',
            field=models.CharField(blank=True, max_length=100, verbose_name='Atividade ou função que executa na ONG, em inglês'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='atividade',
            field=models.CharField(blank=True, max_length=100, verbose_name='atividade ou função que executa na ONG'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='depoimento',
            field=models.TextField(blank=True, verbose_name='depoimento sobre a ONG'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='ong/static/images/', verbose_name='foto - utilize este campo para carregar uma nova foto ou substituir foto existente'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='photo64',
            field=models.TextField(blank=True, null=True, verbose_name='foto - se este campo estiver preenchido, foto já existe no sistema!'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='statement',
            field=models.TextField(blank=True, verbose_name='Depoimento sobre a ONG, em inglês'),
        ),
    ]
