# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0031_auto_20171128_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='nome completo'),
        ),
    ]
