# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0032_auto_20171128_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='activity',
            field=models.CharField(blank=True, max_length=100, verbose_name='Atividade ou função que exerce na ONG, em inglês'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='atividade',
            field=models.CharField(blank=True, max_length=100, verbose_name='atividade ou função que exerce na ONG'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='photo64',
            field=models.TextField(blank=True, null=True, verbose_name='foto - se este campo estiver preenchido, foto já existe no sistema'),
        ),
    ]
