# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0033_auto_20171128_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='possuiPhoto',
            field=models.BooleanField(default=False, verbose_name='possui foto?'),
        ),
    ]
