# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0035_auto_20171128_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='apagarPhoto',
            field=models.BooleanField(default=False, verbose_name='marque esta opção apenas se deseja excluir a foto de capa ao salvar'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='ong/static/images/', verbose_name='foto de capa do projeto'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='photo64',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='possuiPhoto',
            field=models.BooleanField(default=False, verbose_name='possui foto de capa?'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='photo64',
            field=models.TextField(editable=False, null=True),
        ),
    ]
