# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0036_auto_20171128_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceria',
            name='apagarPhoto',
            field=models.BooleanField(default=False, verbose_name='marque esta opção apenas se deseja excluir a foto ao salvar'),
        ),
        migrations.AddField(
            model_name='parceria',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='ong/static/images/', verbose_name='foto - utilize este campo para carregar uma nova foto ou substituir foto existente'),
        ),
        migrations.AddField(
            model_name='parceria',
            name='photo64',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='parceria',
            name='possuiPhoto',
            field=models.BooleanField(default=False, verbose_name='possui foto?'),
        ),
        migrations.AlterField(
            model_name='parceria',
            name='responsavel',
            field=models.CharField(blank=True, max_length=100, verbose_name='nome do responsável ou pessoa para contato principal (Exemplo: João Augusto)'),
        ),
        migrations.AlterField(
            model_name='parceria',
            name='type',
            field=models.CharField(choices=[('E1', 'COMMUNITY'), ('E2', 'UNIVERSITY'), ('E3', 'COMPANY')], max_length=2, verbose_name='tipo, em inglês'),
        ),
    ]
