# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0037_auto_20171128_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='activity',
            field=models.CharField(blank=True, help_text='atividade ou função que este membro exerce na ONG', max_length=100, verbose_name='atividade, em inglês'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='apagarPhoto',
            field=models.BooleanField(default=False, help_text='marque esta opção apenas se deseja excluir a foto ao salvar', verbose_name='excluir foto?'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='atividade',
            field=models.CharField(blank=True, help_text='atividade ou função que este membro exerce na ONG', max_length=100, verbose_name='atividade'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='dataFim',
            field=models.DateField(blank=True, help_text='preencher, se houver', null=True, verbose_name='data de término das atividades'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='photo',
            field=models.ImageField(blank=True, help_text='utilize este campo para carregar uma nova foto ou substituir foto existente', null=True, upload_to='ong/static/images/', verbose_name='foto'),
        ),
    ]
