# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0039_auto_20171128_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceria',
            name='apagarPhoto',
            field=models.BooleanField(default=False, help_text='Marque esta opção apenas se deseja excluir a foto ao salvar', verbose_name='excluir foto?'),
        ),
        migrations.AlterField(
            model_name='parceria',
            name='nome',
            field=models.CharField(help_text='Exemplo: USP ou UFSCar', max_length=100, verbose_name='nome do parceiro'),
        ),
        migrations.AlterField(
            model_name='parceria',
            name='photo',
            field=models.ImageField(blank=True, help_text='Utilize este campo para carregar uma nova foto ou substituir foto existente', null=True, upload_to='ong/static/images/', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='parceria',
            name='responsavel',
            field=models.CharField(blank=True, help_text='Nome do responsável ou pessoa para contato principal (Exemplo: João Augusto)', max_length=100, verbose_name='responsável'),
        ),
        migrations.AlterField(
            model_name='parceria',
            name='telefone',
            field=models.CharField(blank=True, help_text='telefone principal para contato com o parceiro', max_length=20, verbose_name='telefone do parceiro'),
        ),
    ]
