# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0043_auto_20171128_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='membros',
            field=models.ManyToManyField(blank=True, help_text='Membros responsáveis pelo projeto, se houver.', to='ong.Membro', verbose_name='membros'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='parceiros',
            field=models.ManyToManyField(blank=True, help_text='Parceiros envolvidos com o projeto, se houver.', to='ong.Parceria', verbose_name='parceiros'),
        ),
    ]
