# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0044_auto_20171128_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanhaparadoacoes',
            name='dataFim',
            field=models.DateField(blank=True, help_text='Até quando o link fica disponível no site?', null=True, verbose_name='data de término da campanha'),
        ),
        migrations.AlterField(
            model_name='campanhaparadoacoes',
            name='description',
            field=models.TextField(blank=True, verbose_name='descrição, em inglês'),
        ),
        migrations.AlterField(
            model_name='campanhaparadoacoes',
            name='link',
            field=models.URLField(help_text='Onde o dinheiro será arrecadado', verbose_name='link para campanha'),
        ),
        migrations.AlterField(
            model_name='campanhaparadoacoes',
            name='projeto',
            field=models.ForeignKey(help_text='Projeto para o qual a campanha foi criada, se aplicável', on_delete=django.db.models.deletion.CASCADE, to='ong.Projeto', verbose_name='projeto'),
        ),
        migrations.AlterField(
            model_name='campanhaparadoacoes',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='título, em inglês'),
        ),
        migrations.AlterField(
            model_name='campanhaparadoacoes',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='título da campanha'),
        ),
    ]
