# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0047_auto_20171128_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depoimentosobreprojeto',
            name='depoimento',
            field=models.TextField(verbose_name='depoimento sobre projeto'),
        ),
        migrations.AlterField(
            model_name='depoimentosobreprojeto',
            name='idade',
            field=models.PositiveIntegerField(blank=True, help_text='Idade de quem fez o depoimento', verbose_name='idade'),
        ),
        migrations.AlterField(
            model_name='depoimentosobreprojeto',
            name='linkVideo',
            field=models.URLField(blank=True, help_text='Link para depoimento em vídeo, se houver', verbose_name='link para vídeo'),
        ),
        migrations.AlterField(
            model_name='depoimentosobreprojeto',
            name='nome',
            field=models.CharField(help_text='Nome de quem fez o depoimento', max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='depoimentosobreprojeto',
            name='projeto',
            field=models.ForeignKey(help_text='Projeto para o qual o depoimento foi feito', on_delete=django.db.models.deletion.CASCADE, to='ong.Projeto', verbose_name='projeto'),
        ),
    ]
