# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0048_auto_20171128_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depoimentosobreprojeto',
            name='statement',
            field=models.TextField(blank=True, verbose_name='depoimento sobre projeto, em inglês'),
        ),
    ]
