# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0049_auto_20171128_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='depoimentosobreprojeto',
            name='apagarPhoto',
            field=models.BooleanField(default=False, help_text='Marque esta opção apenas se deseja excluir a foto ao salvar', verbose_name='excluir foto?'),
        ),
        migrations.AddField(
            model_name='depoimentosobreprojeto',
            name='photo',
            field=models.ImageField(blank=True, help_text='foto de quem fez o depoimento, se houver', null=True, upload_to='ong/static/images/', verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='depoimentosobreprojeto',
            name='photo64',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='depoimentosobreprojeto',
            name='possuiPhoto',
            field=models.BooleanField(default=False, verbose_name='possui foto?'),
        ),
    ]
