# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0050_auto_20171128_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depoimentosobreprojeto',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto de quem fez o depoimento, se houver. Utilize este campo para carregar uma nova foto ou substituir foto existente', null=True, upload_to='ong/static/images/', verbose_name='foto'),
        ),
    ]
