# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0051_auto_20171128_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='photo',
            field=models.ImageField(blank=True, help_text='Utilize este campo para carregar uma nova foto ou substituir foto existente', null=True, upload_to='ong/static/images/', verbose_name='foto de capa do projeto'),
        ),
    ]
