# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0052_auto_20171128_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='apagarPhoto',
            field=models.BooleanField(default=False, help_text='Marque esta opção apenas se deseja excluir a foto de capa ao salvar', verbose_name='excluir foto de capa?'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='linkFotos',
            field=models.URLField(blank=True, verbose_name='link para álbum de fotos da notícia'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='linkVideo',
            field=models.URLField(blank=True, verbose_name='link para vídeo sobre a notícia'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='photo',
            field=models.ImageField(blank=True, help_text='Utilize este campo para carregar uma nova foto ou substituir foto existente', null=True, upload_to='ong/static/images/', verbose_name='foto de capa'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='photo64',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='possuiPhoto',
            field=models.BooleanField(default=False, verbose_name='possui foto de capa?'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data',
            field=models.DateField(help_text='Corresponde à data que aparecerá no site', verbose_name='data de postagem'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='link',
            field=models.URLField(blank=True, help_text='Exemplo: link para um post no Facebook ou em um site externo', verbose_name='link para conteúdo externo'),
        ),
    ]
