# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0053_auto_20171128_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='link',
            field=models.URLField(blank=True, help_text='Exemplo: link para um post no Facebook ou para um site externo', verbose_name='link para conteúdo externo'),
        ),
    ]
