# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0054_auto_20171128_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receitadedoacoes',
            name='meio_pagto',
        ),
        migrations.RemoveField(
            model_name='receitadedoacoes',
            name='pay_method',
        ),
        migrations.AddField(
            model_name='receitadedoacoes',
            name='meioPagto',
            field=models.CharField(choices=[('PM1', 'PayPal'), ('PM2', 'Vakinha'), ('PM3', 'Boleto'), ('PM4', 'Depósito Bancário'), ('PM5', 'Transferência Bancária'), ('PM5', 'Dinheiro'), ('PM7', 'Outro')], default='', help_text='Meio de pagamento utilizado pelo doador', max_length=3, verbose_name='meio de pagamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receitadedoacoes',
            name='payMethod',
            field=models.CharField(choices=[('EM1', 'PayPal'), ('EM2', 'Vakinha'), ('EM3', 'Boleto'), ('EM4', 'Bank Deposit'), ('EM5', 'Bank Transfer'), ('EM5', 'Cash'), ('EM7', 'Other')], default='', help_text='Meio de pagamento utilizado pelo doador', max_length=3, verbose_name='meio de pagamento, em inglês'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receitadedoacoes',
            name='anonimo',
            field=models.BooleanField(help_text='Marque este campo apenas se esta foi uma doação anônima; deixe em branco caso contrário)', verbose_name='doação anônima?'),
        ),
        migrations.AlterField(
            model_name='receitadedoacoes',
            name='comentarios',
            field=models.CharField(blank=True, help_text='Exemplo: nome do projeto ou evento para o qual o valor foi utilizado', max_length=100, verbose_name='outras informações'),
        ),
        migrations.AlterField(
            model_name='receitadedoacoes',
            name='nome',
            field=models.CharField(blank=True, help_text='Preencha com o nome do doador apenas se a doação não foi anônima, isto é, o doador gostaria de ser reconhecido por isso', max_length=100, verbose_name='nome do doador'),
        ),
        migrations.AlterField(
            model_name='receitadedoacoes',
            name='usage',
            field=models.CharField(choices=[('E1', 'Administration and maintenance tasks'), ('E2', 'Investments on existing projects'), ('E3', 'Creation of new projects'), ('E4', 'Resources and materials acquisition'), ('E5', 'Training of team members'), ('E6', 'Events and celebrations'), ('E7', 'Other demands')], help_text='Como esse valor foi ou será gasto/utilizado pela ONG, em ingles', max_length=2, verbose_name='forma de utilização, em inglês'),
        ),
        migrations.AlterField(
            model_name='receitadedoacoes',
            name='utilizacao',
            field=models.CharField(choices=[('P1', 'Manutenção administrativa da ONG'), ('P2', 'Aplicação em projetos existentes'), ('P3', 'Criação de novos projetos'), ('P4', 'Aquisição de recursos e materiais'), ('P5', 'Treinamentos para membros da equipe'), ('P6', 'Eventos e comemorações'), ('P7', 'Outras finalidades')], help_text='Como esse valor foi ou será gasto/utilizado pela ONG?', max_length=2, verbose_name='forma de utilização'),
        ),
    ]
