# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0055_auto_20171128_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacoesGeraisONG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missao', models.TextField(verbose_name='missão')),
                ('visao', models.TextField(verbose_name='visão')),
                ('valores', models.TextField(verbose_name='valores')),
                ('principios', models.TextField(verbose_name='principios')),
                ('proverbio', models.TextField(help_text='Frase que será mostrada na página inicial', verbose_name='provérbio')),
                ('nome', models.CharField(max_length=100, verbose_name='nome da ONG')),
                ('endereco', models.CharField(max_length=200, verbose_name='endereco da ONG')),
                ('email', models.CharField(max_length=100, verbose_name='email da ONG')),
                ('telefone', models.CharField(max_length=20, verbose_name='telefone da ONG')),
                ('facebook', models.URLField(blank=True, verbose_name='facebook')),
                ('twitter', models.URLField(blank=True, verbose_name='twitter')),
                ('instagram', models.URLField(blank=True, verbose_name='instagram')),
                ('youtube', models.URLField(blank=True, verbose_name='youtube')),
            ],
            options={
                'verbose_name': 'informações gerais',
                'verbose_name_plural': 'informações gerais',
            },
        ),
    ]
