# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0056_informacoesgeraisong'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoesgeraisong',
            name='mission',
            field=models.TextField(default='', verbose_name='missão, em inglês'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informacoesgeraisong',
            name='principles',
            field=models.TextField(default='', verbose_name='principios, em inglês'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informacoesgeraisong',
            name='proverb',
            field=models.TextField(default='', help_text='Frase que será mostrada na página inicial', verbose_name='provérbio, em inglês'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informacoesgeraisong',
            name='values',
            field=models.TextField(default='', verbose_name='valores, em inglês'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informacoesgeraisong',
            name='vision',
            field=models.TextField(default='', verbose_name='visão, em inglês'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informacoesgeraisong',
            name='email',
            field=models.CharField(max_length=100, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='informacoesgeraisong',
            name='endereco',
            field=models.CharField(max_length=200, verbose_name='endereco'),
        ),
        migrations.AlterField(
            model_name='informacoesgeraisong',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='telefone'),
        ),
    ]
