# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0057_auto_20171129_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacoesgeraisong',
            name='nome',
            field=models.CharField(help_text='Nome da ONG, que aparecerá em todos os lugares', max_length=100, verbose_name='Nome'),
        ),
    ]
