# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0058_auto_20171129_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoesgeraisong',
            name='photo1',
            field=models.URLField(blank=True, help_text='URL da foto que será exibida na home', verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='informacoesgeraisong',
            name='photo10',
            field=models.URLField(blank=True, help_text='URL da foto que será exibida na home', verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='informacoesgeraisong',
            name='photo2',
            field=models.URLField(blank=True, help_text='URL da foto que será exibida na home', verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='informacoesgeraisong',
            name='photo3',
            field=models.URLField(blank=True, help_text='URL da foto que será exibida na home', verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='informacoesgeraisong',
            name='photo4',
            field=models.URLField(blank=True, help_text='URL da foto que será exibida na home', verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='informacoesgeraisong',
            name='photo5',
            field=models.URLField(blank=True, help_text='URL da foto que será exibida na home', verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='informacoesgeraisong',
            name='photo6',
            field=models.URLField(blank=True, help_text='URL da foto que será exibida na home', verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='informacoesgeraisong',
            name='photo7',
            field=models.URLField(blank=True, help_text='URL da foto que será exibida na home', verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='informacoesgeraisong',
            name='photo8',
            field=models.URLField(blank=True, help_text='URL da foto que será exibida na home', verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='informacoesgeraisong',
            name='photo9',
            field=models.URLField(blank=True, help_text='URL da foto que será exibida na home', verbose_name='foto'),
        ),
    ]
