# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0059_auto_20171201_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='link',
            field=models.URLField(blank=True, help_text='Exemplo: link para uma notícia no São Carlos Agora ou outro site ou algum post no Facebook', verbose_name='link para conteúdo externo'),
        ),
    ]
