# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0060_auto_20171210_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='link',
            field=models.URLField(blank=True, help_text='Exemplo: link para uma notícia no São Carlos Agora ou outro site', verbose_name='link para conteúdo externo'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='linkFotos',
            field=models.URLField(blank=True, verbose_name='link para álbum de fotos da notícia no Facebook'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='linkVideo',
            field=models.URLField(blank=True, verbose_name='link para vídeo sobre a notícia (Youtube ou Facebook)'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='linkFotos',
            field=models.URLField(blank=True, verbose_name='link para álbum de fotos do projeto no Facebook'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='linkVideo',
            field=models.URLField(blank=True, verbose_name='link para vídeo do projeto (Youtube ou Facebook)'),
        ),
    ]
