# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0061_auto_20171210_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanhaparadoacoes',
            name='valorArrecadado',
            field=models.FloatField(blank=True, null=True, verbose_name='valor arrecadado (até o final da campanha)'),
        ),
        migrations.AddField(
            model_name='campanhaparadoacoes',
            name='valorEsperado',
            field=models.FloatField(default=0, verbose_name='valor esperado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informacoesgeraisong',
            name='proverb',
            field=models.TextField(help_text='Frase que será mostrada na página inicial', max_length=100, verbose_name='provérbio, em inglês'),
        ),
        migrations.AlterField(
            model_name='informacoesgeraisong',
            name='proverbio',
            field=models.TextField(help_text='Frase que será mostrada na página inicial', max_length=100, verbose_name='provérbio'),
        ),
    ]
